version: '2'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - dupl
    - unparam
    - gocritic
    - funlen
    - goconst
    - unconvert
    - bodyclose
    - sqlclosecheck
    - gomodguard
    - revive
    - gosec
    - forbidigo
  settings:
    govet:
      enable-all: true
    revive:
      rules:
        - name: var-naming
          disabled: true

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - goimports
