CREATE TABLE IF NOT EXISTS `test`(
  `id` BIGINT(20) UNSIGNED AUTO_INCREMENT,
  `tp` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
